### ISSUE TITLE
Is the project alive? Join to another OSS!

### ISSUE THREAD

**Issue by Lancetnik** [Voltane-EU/asyncapi-docgen#1]
@mstingl 
Hi there! I am working on another OSS Project: the [**Propan**](https://github.com/Lancetnik/Propan) framework - a little framework to build microservises on top of various Message Brokers. One of the project fetures - autogenerated and hosted **AsyncAPI** spec.
So, I have a some *pydantic* classes to implement **AsyncAPI** schema generation. Now I want to move them to separated package, but first I found your one.
If you interested in **AsyncAPI** in Python-wold we can build a package together (based on this package or another one) or I can do it alone 😞

**Comment by mstingl** [comment]
Hey, yes the Project is alive, even tough it's currently in an early alpha state.
I would be excited to join forces and expand this package (or create a new one, if there would be too many breaking changes). 🙂

**Comment by Lancetnik** [comment]
Okey, so can I fork this package, extend it and try to migrate existed **Propan** functionality to this? And can you merge these changes after?

**Comment by mstingl** [comment]
sure ;)

**Comment by Lancetnik** [comment]
Great! Let's write some code 🔥
